### ISSUE TITLE
./team.html`s css is broken

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Openly-Website#5]
![image](https://user-images.githubusercontent.com/68120127/204691295-3120b8c6-0152-4331-b7f3-7cc9bdc5efe6.png)

**Comment by showierdata9978** [comment]
until you open console?

**Comment by showierdata9978** [comment]
it was broken when i first loaded the site, then it worked after i opened the console

**Comment by williamhorning** [comment]
seems to be fixed in my latest commit
